[workspace]
members = [ "common", "derive", "lib", "tool"] 
resolver = "2"
     
[workspace.package]
name = "iepub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
